version: 0.2
env:
  variables:
    S3_BUCKET: "angulartest.angulardeploy.com"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
     commands:
      - aws s3 sync dist/angulartest/ s3://angulartest.angulardeploy.com --delete
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes